# Generated by Django 5.2 on 2025-05-10 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_checkpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='MaintenanceRecord',
        ),
        migrations.CreateModel(
            name='MaintenanceCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('is_checked', models.BooleanField(default=False)),
                ('MaintenanceRecord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='inventory.maintenancerecord')),
            ],
        ),
    ]
