# Generated by Django 5.2 on 2025-05-10 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_checkpoint_maintenancerecord_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='is_checked',
        ),
    ]
