# Generated by Django 5.2 on 2025-05-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_checkpoint_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
