# Generated by Django 5.2 on 2025-05-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_maintenancerecord_maintenance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerecord',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
